language: node_js
node_js:
  - '12'
  - '10'
  - '9'
install:
  - npm install

stages:
  - name: deploy

jobs:
  include:
    - stage: test
      script:
        - node --version
        - npm --version
        - echo "Test Started..."
        - npm test
        - echo "Test Finished"

    - stage: deploy
      script:
        - echo "npm Deploy Started"
        - npm --version
        - echo "npm Build Finished"

      deploy:
        provider: npm
        email: moriyuan@techfin.ai
        skip_cleanup: true
        on:
          branch: master
